import './globals.css'
import { Poppins } from 'next/font/google'
import MenuBar from '@/Components/util/MenuBar'
import Footer from '@/Components/util/Footer'
import Head from 'next/head'
const poppins = Poppins({
    weight: ['400', '500', '600', '700'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    variable: '--font-poppins',
    display: 'swap'
})

export const metadata = {
    title: 'Chainplay',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en' >
            {/* <Head>
                <title>{metadata.title}</title>
                <link rel="shortcut icon" href="/favicon.ico" />
            </Head> */}
            <body className={`${poppins.className} dark:bg-black-gray relative`}  suppressHydrationWarning={true} >
                <MenuBar />
                <div>
                    <div className='xl:w-11/12 2xl:w-[1344px] mx-auto'>{children}</div>
                </div>
                <Footer />
                <div className='deep-shadow-blur hidden dark:block'></div>
            </body>
        </html>
    )
}
